version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      replicas: 1

  auth:
    image: cyberadvance/authen-service
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/auth
    deploy:
      replicas: 1